In [1]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
import pandas as pd
import tensorflow as tf

# Import our input dataset
attrition_df= pd.read_csv("Resources/HR-Employee-Attrition.csv")
attrition_df

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1465,36,No,Travel_Frequently,884,Research & Development,23,2,Medical,1,2061,...,3,80,1,17,3,3,5,2,0,3
1466,39,No,Travel_Rarely,613,Research & Development,6,1,Medical,1,2062,...,1,80,1,9,5,3,7,7,1,7
1467,27,No,Travel_Rarely,155,Research & Development,4,3,Life Sciences,1,2064,...,2,80,1,6,0,3,6,2,0,3
1468,49,No,Travel_Frequently,1023,Sales,2,3,Medical,1,2065,...,4,80,0,17,3,2,9,6,0,8
1469,34,No,Travel_Rarely,628,Research & Development,8,3,Medical,1,2068,...,1,80,0,6,3,4,4,3,1,2

In [2]:
# Generate our categorical variable list
attrition_cat=attrition_df.dtypes[attrition_df.dtypes == "object"].index.tolist()
attrition_cat

['Attrition',
 'BusinessTravel',
 'Department',
 'EducationField',
 'Gender',
 'JobRole',
 'MaritalStatus',
 'Over18',
 'OverTime']

In [3]:
# Check the number of unique values in each column
attrition_df[attrition_cat].nunique()

Attrition         2
BusinessTravel    3
Department        3
EducationField    6
Gender            2
JobRole           9
MaritalStatus     3
Over18            1
OverTime          2
dtype: int64

In [4]:
# Create a OneHotEncoder instance
enc= OneHotEncoder(sparse=False)

# Fit and transform the OneHotEncoder using the categorical variable list
encode_df=pd.DataFrame(enc.fit_transform(attrition_df[attrition_cat]))

# Add the encoded variable names to the DataFrame
encode_df.columns=enc.get_feature_names(attrition_cat)
encode_df.head()

,Attrition_No,Attrition_Yes,BusinessTravel_Non-Travel,BusinessTravel_Travel_Frequently,BusinessTravel_Travel_Rarely,Department_Human Resources,Department_Research & Development,Department_Sales,EducationField_Human Resources,EducationField_Life Sciences,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [5]:
# Merge one-hot encoded features and drop the originals
attrition_df=attrition_df.merge(encode_df,left_index=True,right_index=True)
attrition_df=attrition_df.drop(attrition_cat,1)
attrition_df.head()

,Age,DailyRate,DistanceFromHome,Education,EmployeeCount,EmployeeNumber,EnvironmentSatisfaction,HourlyRate,JobInvolvement,JobLevel,...,JobRole_Research Director,JobRole_Research Scientist,JobRole_Sales Executive,JobRole_Sales Representative,MaritalStatus_Divorced,MaritalStatus_Married,MaritalStatus_Single,Over18_Y,OverTime_No,OverTime_Yes
0,41,1102,1,2,1,1,2,94,3,2,...,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
1,49,279,8,1,1,2,3,61,2,2,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
2,37,1373,2,2,1,4,4,92,2,1,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
3,33,1392,3,4,1,5,4,56,3,1,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
4,27,591,2,1,1,7,1,40,3,1,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0

In [6]:
# Split our preprocessed data into our features and target arrays
y=attrition_df["Attrition_Yes"].values
X=attrition_df.drop(["Attrition_Yes","Attrition_No"],1).values

# Split the preprocessed data into a training and testing dataset
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=78)

In [7]:
# Create a StandardScaler instance
scaler=StandardScaler()

# Fit the StandardScaler
X_scaler=scaler.fit(X_train)

# Scale the data
X_train_scaled= X_scaler.transform(X_train)
X_test_scaled= X_scaler.transform(X_test)

In [8]:
X_test_scaled.shape

(368, 55)

In [9]:
X_train_scaled.shape

(1102, 55)

In [10]:
X_train.shape

(1102, 55)

In [11]:
X_train[0]

array([3.3000e+01, 1.1800e+02, 1.6000e+01, 3.0000e+00, 1.0000e+00,
       8.1900e+02, 1.0000e+00, 6.9000e+01, 3.0000e+00, 2.0000e+00,
       1.0000e+00, 5.3240e+03, 2.6507e+04, 5.0000e+00, 1.5000e+01,
       3.0000e+00, 3.0000e+00, 8.0000e+01, 0.0000e+00, 6.0000e+00,
       3.0000e+00, 3.0000e+00, 3.0000e+00, 2.0000e+00, 0.0000e+00,
       2.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 1.0000e+00, 1.0000e+00, 1.0000e+00, 0.0000e+00])

In [12]:
# Define the model - deep neural net
number_input_feature= len(X_train[0])
hidden_node_layer1=8
hidden_node_layer2=5

nn=tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units= hidden_node_layer1,input_dim=number_input_feature,activation="relu"))

#second input layer
nn.add(tf.keras.layers.Dense(units=hidden_node_layer2,activation="relu"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1,activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 8)                 448
_________________________________________________________________
dense_1 (Dense)              (None, 5)                 45
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 6
=================================================================
Total params: 499
Trainable params: 499
Non-trainable params: 0
_________________________________________________________________

In [13]:
number_input_feature

55

In [14]:
# Import checkpoint dependencies
import os
from tensorflow.keras.callbacks import ModelCheckpoint

# Define the checkpoint path and filenames
os.makedirs("checkpoints",exist_ok=True)
checkpoint_path="checkpoints/weights.{epoch:02d}.hdf5"

In [17]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Create a callback that saves the model's weights every epoch
cp_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq=150)

# Train the model
fit_model = nn.fit(X_train_scaled,y_train,epochs=100,callbacks=[cp_callback])

# Train the model
#fit_model=nn.fit(X_train,y_train,epochs=100)

Epoch 1/100
35/35 [==============================] - 0s 835us/step - loss: 0.1688 - accuracy: 0.9356
Epoch 2/100
35/35 [==============================] - 0s 975us/step - loss: 0.1659 - accuracy: 0.9338
Epoch 3/100
35/35 [==============================] - 0s 895us/step - loss: 0.1649 - accuracy: 0.9356
Epoch 4/100
35/35 [==============================] - 0s 941us/step - loss: 0.1645 - accuracy: 0.9319
Epoch 5/100
 1/35 [..............................] - ETA: 0s - loss: 0.1376 - accuracy: 0.9375
Epoch 00005: saving model to checkpoints\weights.05.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1628 - accuracy: 0.9383
Epoch 6/100
35/35 [==============================] - 0s 945us/step - loss: 0.1615 - accuracy: 0.9365
Epoch 7/100
35/35 [==============================] - 0s 1ms/step - loss: 0.1611 - accuracy: 0.9347
Epoch 8/100
35/35 [==============================] - 0s 810us/step - loss: 0.1605 - accuracy: 0.9374
Epoch 9/100
 1/35 [..............................] - ETA: 0s - loss: 0.1037 - accuracy: 0.9688
Epoch 00009: saving model to checkpoints\weights.09.hdf5
35/35 [==============================] - 0s 941us/step - loss: 0.1596 - accuracy: 0.9338
Epoch 10/100
35/35 [==============================] - 0s 766us/step - loss: 0.1595 - accuracy: 0.9356
Epoch 11/100
35/35 [==============================] - 0s 707us/step - loss: 0.1594 - accuracy: 0.9374
Epoch 12/100
35/35 [==============================] - 0s 782us/step - loss: 0.1580 - accuracy: 0.9374
Epoch 13/100
 1/35 [..............................] - ETA: 0s - loss: 0.2223 - accuracy: 0.8750
Epoch 00013: saving model to checkpoints\weights.13.hdf5
35/35 [==============================] - 0s 1000us/step - loss: 0.1566 - accuracy: 0.9356
Epoch 14/100
35/35 [==============================] - 0s 735us/step - loss: 0.1577 - accuracy: 0.9383
Epoch 15/100
35/35 [==============================] - 0s 740us/step - loss: 0.1566 - accuracy: 0.9365
Epoch 16/100
35/35 [==============================] - 0s 693us/step - loss: 0.1555 - accuracy: 0.9347
Epoch 17/100
35/35 [==============================] - 0s 794us/step - loss: 0.1540 - accuracy: 0.9374
Epoch 18/100
 1/35 [..............................] - ETA: 0s - loss: 0.1350 - accuracy: 0.9062
Epoch 00018: saving model to checkpoints\weights.18.hdf5
35/35 [==============================] - 0s 912us/step - loss: 0.1533 - accuracy: 0.9392
Epoch 19/100
35/35 [==============================] - 0s 736us/step - loss: 0.1530 - accuracy: 0.9383
Epoch 20/100
35/35 [==============================] - 0s 794us/step - loss: 0.1520 - accuracy: 0.9383
Epoch 21/100
35/35 [==============================] - 0s 714us/step - loss: 0.1519 - accuracy: 0.9410
Epoch 22/100
 1/35 [..............................] - ETA: 0s - loss: 0.0664 - accuracy: 1.0000
Epoch 00022: saving model to checkpoints\weights.22.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1505 - accuracy: 0.9410
Epoch 23/100
35/35 [==============================] - 0s 852us/step - loss: 0.1495 - accuracy: 0.9401
Epoch 24/100
35/35 [==============================] - 0s 840us/step - loss: 0.1504 - accuracy: 0.9374
Epoch 25/100
35/35 [==============================] - 0s 794us/step - loss: 0.1497 - accuracy: 0.9383
Epoch 26/100
 1/35 [..............................] - ETA: 0s - loss: 0.1448 - accuracy: 0.9688
Epoch 00026: saving model to checkpoints\weights.26.hdf5
35/35 [==============================] - 0s 993us/step - loss: 0.1481 - accuracy: 0.9401
Epoch 27/100
35/35 [==============================] - 0s 815us/step - loss: 0.1467 - accuracy: 0.9392
Epoch 28/100
35/35 [==============================] - 0s 769us/step - loss: 0.1456 - accuracy: 0.9437
Epoch 29/100
35/35 [==============================] - 0s 713us/step - loss: 0.1449 - accuracy: 0.9446
Epoch 30/100
 1/35 [..............................] - ETA: 0s - loss: 0.1169 - accuracy: 0.9688
Epoch 00030: saving model to checkpoints\weights.30.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1445 - accuracy: 0.9428
Epoch 31/100
35/35 [==============================] - 0s 825us/step - loss: 0.1438 - accuracy: 0.9410
Epoch 32/100
35/35 [==============================] - 0s 739us/step - loss: 0.1437 - accuracy: 0.9383
Epoch 33/100
35/35 [==============================] - 0s 724us/step - loss: 0.1433 - accuracy: 0.9401
Epoch 34/100
35/35 [==============================] - 0s 824us/step - loss: 0.1415 - accuracy: 0.9437
Epoch 35/100
 1/35 [..............................] - ETA: 0s - loss: 0.1496 - accuracy: 0.9375
Epoch 00035: saving model to checkpoints\weights.35.hdf5
35/35 [==============================] - 0s 986us/step - loss: 0.1419 - accuracy: 0.9437
Epoch 36/100
35/35 [==============================] - 0s 771us/step - loss: 0.1409 - accuracy: 0.9437
Epoch 37/100
35/35 [==============================] - 0s 800us/step - loss: 0.1405 - accuracy: 0.9419
Epoch 38/100
35/35 [==============================] - 0s 742us/step - loss: 0.1399 - accuracy: 0.9419
Epoch 39/100
 1/35 [..............................] - ETA: 0s - loss: 0.1026 - accuracy: 1.0000
Epoch 00039: saving model to checkpoints\weights.39.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1391 - accuracy: 0.9437
Epoch 40/100
35/35 [==============================] - 0s 778us/step - loss: 0.1385 - accuracy: 0.9465
Epoch 41/100
35/35 [==============================] - 0s 820us/step - loss: 0.1384 - accuracy: 0.9419
Epoch 42/100
35/35 [==============================] - 0s 862us/step - loss: 0.1366 - accuracy: 0.9446
Epoch 43/100
 1/35 [..............................] - ETA: 0s - loss: 0.1542 - accuracy: 0.9375
Epoch 00043: saving model to checkpoints\weights.43.hdf5
35/35 [==============================] - 0s 999us/step - loss: 0.1361 - accuracy: 0.9465
Epoch 44/100
35/35 [==============================] - 0s 904us/step - loss: 0.1356 - accuracy: 0.9474
Epoch 45/100
35/35 [==============================] - 0s 834us/step - loss: 0.1346 - accuracy: 0.9474
Epoch 46/100
35/35 [==============================] - 0s 913us/step - loss: 0.1349 - accuracy: 0.9465
Epoch 47/100
35/35 [==============================] - 0s 753us/step - loss: 0.1352 - accuracy: 0.9483
Epoch 48/100
 1/35 [..............................] - ETA: 0s - loss: 0.2481 - accuracy: 0.9062
Epoch 00048: saving model to checkpoints\weights.48.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1338 - accuracy: 0.9437
Epoch 49/100
35/35 [==============================] - 0s 851us/step - loss: 0.1332 - accuracy: 0.9456
Epoch 50/100
35/35 [==============================] - 0s 782us/step - loss: 0.1328 - accuracy: 0.9474
Epoch 51/100
35/35 [==============================] - 0s 810us/step - loss: 0.1315 - accuracy: 0.9501
Epoch 52/100
 1/35 [..............................] - ETA: 0s - loss: 0.1024 - accuracy: 0.9688
Epoch 00052: saving model to checkpoints\weights.52.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1312 - accuracy: 0.9492
Epoch 53/100
35/35 [==============================] - 0s 746us/step - loss: 0.1307 - accuracy: 0.9456
Epoch 54/100
35/35 [==============================] - 0s 858us/step - loss: 0.1306 - accuracy: 0.9474
Epoch 55/100
35/35 [==============================] - 0s 849us/step - loss: 0.1303 - accuracy: 0.9474
Epoch 56/100
 1/35 [..............................] - ETA: 0s - loss: 0.1602 - accuracy: 0.9062
Epoch 00056: saving model to checkpoints\weights.56.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1298 - accuracy: 0.9465
Epoch 57/100
35/35 [==============================] - 0s 837us/step - loss: 0.1293 - accuracy: 0.9474
Epoch 58/100
35/35 [==============================] - 0s 704us/step - loss: 0.1293 - accuracy: 0.9437
Epoch 59/100
35/35 [==============================] - 0s 889us/step - loss: 0.1284 - accuracy: 0.9510
Epoch 60/100
 1/35 [..............................] - ETA: 0s - loss: 0.0554 - accuracy: 0.9688
Epoch 00060: saving model to checkpoints\weights.60.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1275 - accuracy: 0.9474
Epoch 61/100
35/35 [==============================] - 0s 895us/step - loss: 0.1258 - accuracy: 0.9501
Epoch 62/100

35/35 [==============================] - 0s 695us/step - loss: 0.1254 - accuracy: 0.9492
Epoch 63/100
35/35 [==============================] - 0s 832us/step - loss: 0.1263 - accuracy: 0.9492
Epoch 64/100
35/35 [==============================] - 0s 804us/step - loss: 0.1270 - accuracy: 0.9465
Epoch 65/100
 1/35 [..............................] - ETA: 0s - loss: 0.2206 - accuracy: 0.8750
Epoch 00065: saving model to checkpoints\weights.65.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1260 - accuracy: 0.9492
Epoch 66/100
35/35 [==============================] - 0s 769us/step - loss: 0.1238 - accuracy: 0.9492
Epoch 67/100
35/35 [==============================] - 0s 899us/step - loss: 0.1243 - accuracy: 0.9474
Epoch 68/100
35/35 [==============================] - 0s 754us/step - loss: 0.1230 - accuracy: 0.9519
Epoch 69/100
 1/35 [..............................] - ETA: 0s - loss: 0.2014 - accuracy: 0.9062
Epoch 00069: saving model to checkpoints\weights.69.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1226 - accuracy: 0.9519
Epoch 70/100
35/35 [==============================] - 0s 818us/step - loss: 0.1210 - accuracy: 0.9528
Epoch 71/100
35/35 [==============================] - 0s 873us/step - loss: 0.1220 - accuracy: 0.9501
Epoch 72/100
35/35 [==============================] - 0s 732us/step - loss: 0.1197 - accuracy: 0.9510
Epoch 73/100
 1/35 [..............................] - ETA: 0s - loss: 0.0572 - accuracy: 0.9688
Epoch 00073: saving model to checkpoints\weights.73.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1207 - accuracy: 0.9483
Epoch 74/100
35/35 [==============================] - 0s 790us/step - loss: 0.1187 - accuracy: 0.9519
Epoch 75/100
35/35 [==============================] - 0s 835us/step - loss: 0.1183 - accuracy: 0.9528
Epoch 76/100
35/35 [==============================] - 0s 768us/step - loss: 0.1179 - accuracy: 0.9510
Epoch 77/100
35/35 [==============================] - 0s 786us/step - loss: 0.1179 - accuracy: 0.9528
Epoch 78/100
 1/35 [..............................] - ETA: 0s - loss: 0.1301 - accuracy: 0.9062
Epoch 00078: saving model to checkpoints\weights.78.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1168 - accuracy: 0.9537
Epoch 79/100
35/35 [==============================] - 0s 875us/step - loss: 0.1161 - accuracy: 0.9555
Epoch 80/100
35/35 [==============================] - 0s 842us/step - loss: 0.1148 - accuracy: 0.9528
Epoch 81/100
35/35 [==============================] - 0s 813us/step - loss: 0.1145 - accuracy: 0.9528
Epoch 82/100
 1/35 [..............................] - ETA: 0s - loss: 0.0539 - accuracy: 1.0000
Epoch 00082: saving model to checkpoints\weights.82.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1143 - accuracy: 0.9519
Epoch 83/100
35/35 [==============================] - 0s 725us/step - loss: 0.1140 - accuracy: 0.9546
Epoch 84/100
35/35 [==============================] - 0s 892us/step - loss: 0.1142 - accuracy: 0.9528
Epoch 85/100
35/35 [==============================] - 0s 766us/step - loss: 0.1123 - accuracy: 0.9528
Epoch 86/100
 1/35 [..............................] - ETA: 0s - loss: 0.0724 - accuracy: 0.9688
Epoch 00086: saving model to checkpoints\weights.86.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1116 - accuracy: 0.9564
Epoch 87/100
35/35 [==============================] - 0s 779us/step - loss: 0.1118 - accuracy: 0.9528
Epoch 88/100
35/35 [==============================] - 0s 813us/step - loss: 0.1106 - accuracy: 0.9546
Epoch 89/100
35/35 [==============================] - 0s 805us/step - loss: 0.1111 - accuracy: 0.9555
Epoch 90/100
 1/35 [..............................] - ETA: 0s - loss: 0.0489 - accuracy: 0.9688
Epoch 00090: saving model to checkpoints\weights.90.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1096 - accuracy: 0.9574
Epoch 91/100
35/35 [==============================] - 0s 876us/step - loss: 0.1111 - accuracy: 0.9510
Epoch 92/100
35/35 [==============================] - 0s 906us/step - loss: 0.1096 - accuracy: 0.9528
Epoch 93/100
35/35 [==============================] - 0s 745us/step - loss: 0.1083 - accuracy: 0.9546
Epoch 94/100
35/35 [==============================] - 0s 791us/step - loss: 0.1072 - accuracy: 0.9546
Epoch 95/100
 1/35 [..............................] - ETA: 0s - loss: 0.0839 - accuracy: 1.0000
Epoch 00095: saving model to checkpoints\weights.95.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1075 - accuracy: 0.9546
Epoch 96/100
35/35 [==============================] - 0s 831us/step - loss: 0.1063 - accuracy: 0.9564
Epoch 97/100
35/35 [==============================] - 0s 701us/step - loss: 0.1058 - accuracy: 0.9564
Epoch 98/100
35/35 [==============================] - 0s 781us/step - loss: 0.1050 - accuracy: 0.9564
Epoch 99/100
 1/35 [..............................] - ETA: 0s - loss: 0.0927 - accuracy: 0.9688
Epoch 00099: saving model to checkpoints\weights.99.hdf5
35/35 [==============================] - 0s 1ms/step - loss: 0.1059 - accuracy: 0.9537
Epoch 100/100
35/35 [==============================] - 0s 882us/step - loss: 0.1051 - accuracy: 0.9574

In [ ]:
# Evaluate the model using the test data
model_loss,model_accuracy=nn.evaluate(X_test,y_test,verbose=2)
print(f"Loss:{model_loss}, Accuracy:{model_accuracy}")

In [ ]:
# Define the model - deep neural net
number_input_features = len(X_train_scaled[0])
#hidden_nodes_layer1 =  24
#hidden_nodes_layer2 = 12

hidden_nodes_layer1 = 8
hidden_nodes_layer2 =5
nn_new = tf.keras.models.Sequential()

# First hidden layer
nn_new.add(
    tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu")
)

# Second hidden layer
nn_new.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))
#nn_new.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="relu"))
#nn_new.add(tf.keras.layers.Dense(units=hidden_nodes_layer4, activation="relu"))
# Output layer
nn_new.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Compile the model
nn_new.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

# Restore the model weights
nn_new.load_weights("checkpoints/weights.100.hdf5")

# Evaluate the model using the test data
model_loss, model_accuracy = nn_new.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

In [ ]:
# Export our model to HDF5 file
nn_new.save("trained_attrition.h5")

In [ ]:
# Import the model to a new object
nn_imported=tf.keras.models.load_model("trained_attrition.h5")

In [ ]:
# Evaluate the completed model using the test data
model_loss,model_accuracy=nn_imported.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")